### ISSUE TITLE
Polymorphic type of `initialized`

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#10]
I noticed recently that the `initialized` attribute is set to either `True`, `False` or `2`. Python is a weakly-typed language, so this doesn't _really_ matter.
But IMHO it feels kinda wrong having an attribute which is sometimes a boolean and sometimes an integer :confused: 

Also, is this an internal-use-only attribute, and should it therefore be renamed to `_initialized` ?

**Comment by Marco-Sulla** [comment]
Booleans ARE integers... :-D

**Comment by Marco-Sulla** [comment]
Well, furthermore Python is *not* weakly-typed. It's *dynamic*, but *strong* typed.

**Comment by lurch** [comment]
:man_shrugging:  Feel free to close this if you want.

My mistake for mixing up weakly-typed and dynamically-typed :wink:

**Comment by Marco-Sulla** [comment]
Anyway, changed to integer, so you're happy ^^
