### ISSUE TITLE
[FEATURE] Create wheels for python 3.11 (and 3.12)

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [Marco-Sulla/python-frozendict#100]
Welcome! Before you write your Feature Request, please read below:

**Is your feature request related to a problem? Please describe.**
When using frozendict on newer versions of python (3.11 and above) I need to compile frozendict.

**Describe the solution you'd like**
Build and release wheels for python 3.11 and 3.12 too.

**Describe alternatives you've considered**

**Additional context**

**Comment by Marco-Sulla** [comment]
Confirmed. Not a big deal, I must say, since it seems to take seconds to build the wheel (C extension is not yet available for python 3.11+)

**Comment by Marco-Sulla** [comment]
Ok, the pipeline was adapted:
https://github.com/Marco-Sulla/python-frozendict/commit/216c48a2e37ed99bbcac01a02c1e1e3808a93b48

and the wheels for Python 3.11 and 3.12 was uploaded to Pypi:
https://pypi.org/project/frozendict/#files

Can you confirm that the wheels are working?

**Comment by thomasfrederikhoeck** [comment]
It works! Thank you @Marco-Sulla
