### ISSUE TITLE
[BUG] deepcopy doesn't work as expected

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#11]
OS version:
Ubuntu 14.04.6 x64

Python3 version (python3 -V -V):
Python 3.6.8 (default, Dec 25 2018, 00:00:00)
[GCC 4.8.4]

Steps to reproduce:
```python3
>>> from frozendict import frozendict
>>> import copy
>>> fd1 = frozendict({'tuple': (1, 2), 'list': ['a', 'b', 'c']})
>>> fd2 = copy.deepcopy(fd1)
>>> fd2['list'].append('d')
>>> print(fd1)
frozendict({'tuple': (1, 2), 'list': ['a', 'b', 'c', 'd']})
```

After the `deepcopy` I'd expect modifying `fd2` to _not_ also modify `fd1`?
I guess the current `__deepcopy__` implementation would only work if the entire frozendict was hashable (and there's nothing currently in frozendict to ensure that all the values are hashable).
On a side-note, would there be any value (no pun intended) in a frozendict that **did** ensure that all its values were hashable (i.e. entirely immutable) ?

**Comment by Marco-Sulla** [comment]
Try to deepcopy a `tuple`, for example...

**Comment by Marco-Sulla** [comment]
> would only work if the entire frozendict was hashable
Yes, good catch! It's the same behaviour of tuple: if all its values are hashable, it returns itself. On the contrary, it returns a deepcopy.

**Comment by Marco-Sulla** [comment]
> would there be any value (no pun intended) in a frozendict that did ensure that all its values were hashable

No. As tuple, you have to check `hash()`. `hash()` anyway it's lazy and cached, so after the first time you call it, it will be very fast.

**Comment by Marco-Sulla** [comment]
Fixed with https://github.com/Marco-Sulla/python-frozendict/commit/961c3bc87a4d1cc7814a05edc43e961d4363e495

**Comment by lurch** [comment]
I hope you don't think I'm being too nit-picky, but I added some comments on that commit.
