### ISSUE TITLE
[FEATURE] Add frozendict intersections test

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#15]
...where the values in one frozendict don't match the values in the other frozendict. E.g.
```python3
fd1 = frozendict({"spam": 1, "eggs": 2})
fd2 = frozendict({"ham": 3, "eggs": 4})
fd3 = fd1 & fd2
fd4 = fd2 & fd1
```
and then check the contents of `fd3` and `fd4`.

**Comment by Marco-Sulla** [comment]
Fixed with https://github.com/Marco-Sulla/python-frozendict/commit/853865d0d6c04ffde65c2ff276ae7f516c58826d

**Comment by Marco-Sulla** [comment]
Other fixes:

https://github.com/Marco-Sulla/python-frozendict/commit/b9b199279b3627b86a91ee210944975cf9912278

https://github.com/Marco-Sulla/python-frozendict/commit/7ba8b90809af5ff003e799b8c7b0aec4d0d919bd
