### ISSUE TITLE
[BUG] bug in isdisjoint

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#16]
Using the latest `master` branch ( ef555e3dd02d1d9b1341e2a4a2b29b82ae3a1953 at the time of writing)

```python3
>>> from frozendict import frozendict
>>> fd1 = frozendict({'a': 1})
>>> fd2 = frozendict({'c': 5, 'b':4})
>>> fd1.isdisjoint(fd2)
False
>>> fd2.isdisjoint(fd1)
True
```

**Comment by Marco-Sulla** [comment]
Fixed in https://github.com/Marco-Sulla/python-frozendict/commit/5c6b4286fe3f0e51c7cbf220761b6939b85d051b
