### ISSUE TITLE
Please public sdist on PyPI

### ISSUE THREAD

**Issue by sunpoet** [Marco-Sulla/python-frozendict#20]
Could you please publish sdist on PyPI?
It is preferred to build FreeBSD port (devel/py-frozendict) from sdist from PyPI.
Thanks!

**Comment by Marco-Sulla** [comment]
I plan to release a manylinux release. In the meantime there's the pure py implementation.

If you want the optimizied version, I doubt that an sdist will compile it, since my `setup.py` will compile the c extension only if you add an additional argument `c`.

**Comment by sunpoet** [comment]
I manually run "python setup.py sdist" to generate the sdist and it works fine for us.
However, it would be better to download the upstream-generated sdist from PyPI.
Thanks!

**Comment by Marco-Sulla** [comment]
What's the result of this:

```
import frozendict
print(frozendict.c_ext)
```
?

**Comment by Marco-Sulla** [comment]
I added the `sdist` for version  2.0.3 on pypi.

**Comment by sunpoet** [comment]
Thank you for adding the sdist.

I forgot to say that I packaged the sdist locally with minor modification to include the C codes.
% cat MANIFEST.in
recursive-include frozendict/src

**Comment by Marco-Sulla** [comment]
https://github.com/Marco-Sulla/python-frozendict/commit/800d32b71d9ba4b15dfd55c7092f047fbfe30068

**Comment by sunpoet** [comment]
Thanks.
