### ISSUE TITLE
dict.__init__ call in __new__ breaks subclasses with overridden __init__

### ISSUE THREAD

**Issue by DomKennedy** [Marco-Sulla/python-frozendict#21]
`frozendict.__new__` calls `dict.__init__(self, *args, **kwargs)`.

As a result, if a `frozendict` subclass defines its own `__init__` which is incompatible with `dict.__init__`, then its `__new__` call with fail with a confusing error.

For a concrete example, consider the following:

```python

from frozendict import frozendict

class FrozenDefaultDict(frozendict):

    def __init__(self, default_factory, *args, **kwargs):
        super().__init__(*args, **kwargs)
        object.__setattr__(self, '_default_factory', default_factory)

    def __getitem__(self, item):
        try:
            return super().__getitem__(item)
        except KeyError:
            return self._default_factory()

d = FrozenDefaultDict(int, dict(foo=1, bar=2))
print(d['foo'])
print (d['baz'])
```

The above raises an error on construction of `d`:

```
Traceback (most recent call last):
  File "scratch_28.py", line 17, in <module>
    d = FrozenDefaultDict(lambda k: k, dict(foo=1, bar=2))
  File ".venv/lib/python3.6/site-packages/frozendict/core.py", line 52, in __new__
    dict.__init__(self, *args, **kwargs)
TypeError: dict expected at most 1 arguments, got 2
```

If I change the superclass of `FrozenDefaultDict` to be a plain `dict`, the snippet behaves as expected, printing `1` then `0`.

It is both surprising and restrictive that extending `frozendict` in the above manner does not work. 

This can be worked around by extending `__new__` instead of `__init__` and making the appropriate `super().__new__` call, but that feels rather leaky.

Is this behaviour an intentional design decision or a bug?

**Comment by Marco-Sulla** [comment]
This is by design, and it's the default for all immutable objects in the Python stdlib. See https://stackoverflow.com/questions/7255655/how-to-subclass-str-in-python for example.
