### ISSUE TITLE
Type hinting on C extension does not work

### ISSUE THREAD

**Issue by MrCreosote** [Marco-Sulla/python-frozendict#26]
I hope this question isn't too stupid; I've spent a ton of time reading through typing and mypy docs but I'm not getting anywhere.

I'm trying to figure out how to annotate a class field as a frozendict for a data class, e.g.

```python
@dataclass(frozen=True)
class Foo:
    a: frozendict[str, str]
```

Of course, I get `TypeError: 'type' object is not subscriptable` if I do that.

I'm using python 3.8 if that matters.

Thanks!

**Comment by Marco-Sulla** [comment]
In pure Python implementation it works, you can use it for now.

**Comment by MrCreosote** [comment]
Please excuse me if I'm being dense but
```
from frozendict.core import frozendict
@dataclass(frozen=True)
class Foo:
    a: frozendict[str, str]
```
... results in the same `TypeError`.

**Comment by Marco-Sulla** [comment]
In Python 3.9 works:

```
>>> from dataclasses import dataclass
>>> @dataclass(frozen=True)
... class Foo:
...     a: frozendict[str, str]
... 
>>> 
```

**Comment by MrCreosote** [comment]
No, I have to use `Dict` there. Ok, looks like I need to upgrade to 3.9, thanks

**Comment by Marco-Sulla** [comment]
Fixed https://github.com/Marco-Sulla/python-frozendict/commit/ecf771ce2f0ad3c8ff9e9059a40f2e9aed1cac6f
