### ISSUE TITLE
[BUG] `cls` kwarg when instantiating breaks frozendict, but not dict.

### ISSUE THREAD

**Issue by NiklasBeierl** [Marco-Sulla/python-frozendict#27]
First of all thanks for implementing this! The absence of a  frozen dict has always bugged me. 

OS: Arch Linux 5.4.0-72-generic
Python: 3.8.5

Steps to reproduce + actual result:
```
>>>frozendict({"a":2, "b":3, "cls":4})
frozendict({'a': 2, 'b': 3, 'cls': 4})
>>>dict(a=2, b=3, cls=4)
{'a': 2, 'b': 3, 'cls': 4}
>>>frozendict(a=2, b=3, cls=4)
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: __new__() got multiple values for argument 'cls'
``` 
Its not hard to work around, but finding the problem was quite tricky. And it can "lurk" if you create frozen dicts with dynamic keys: E.g. in a setting like this:
```
json1 = get_json_from_somewhere()
json2 = get_json_from_somehwere_else()
frozendict(**json1, **json2)
```

**Comment by Marco-Sulla** [comment]
This is perfectly normal. You are using the pure python version, and `cls` is a common var name for the class variable in `__new__`.

I could make it a positional only parameter, but this way the project will be incompatible with Python less than 3.8. No way.

I suggest you to compile the C Extension.

**Comment by Marco-Sulla** [comment]
Ok, I fixed the "bug" with a terrible workaround. God save my dirty soul :D

**Comment by NiklasBeierl** [comment]
Hey thanks for addressing it! I just loooked at the change and while I am not very familiar with the code, I have an idea.

Maybe god will spare your soul if you do it like this: :smile: 

```
def __new__(*args, **kwargs):
        r"""
        Almost identical to dict.__new__().
        """
        cls, args  = args[0], args[1:]
```

**Comment by Marco-Sulla** [comment]
I suppose this way the error for the missing first argument is different, so no. But thanks for the trick :D
