### ISSUE TITLE
[BUG] Version on PyPi is newer than GitHub

### ISSUE THREAD

**Issue by nzig** [Marco-Sulla/python-frozendict#28]
I noticed PyPi has version 2.0.6, but GitHub still has the newest version as 2.0.4. Could you update the releases on GitHub, so that users can check the changes between 2.0.4 and the newest version?

**Comment by Marco-Sulla** [comment]
Changes are related only to support Conda. You can check the changes since I committed them

**Comment by nzig** [comment]
Thank you for your reply, and your work on this library.

It is currently difficult to check the changes on git, because 2.0.6 is not tagged, and the version is not included in the source (It appears to be in a "`VERSION`" file that is not committed). This makes it difficult to know which git commit was used to create the release on PyPi, other than comparing the sources themselves. I can look at `master`, but that might contain unreleased commits.

I'm not complaining - this is your package and you can do whatever you want - but it would be easier for users to upgrade versions if it's easy to see what changes are included in a release.

Thanks again!

**Comment by Marco-Sulla** [comment]
`VERSION` file is up to date:
https://github.com/Marco-Sulla/python-frozendict/blob/master/frozendict/VERSION

**Comment by nzig** [comment]
Thanks. I must have missed that by looking in the root directory instead.
