### ISSUE TITLE
`deepcopy(frozendict[<key type>, <value type>])` returns empty dict instead of type

### ISSUE THREAD

**Issue by JacobHayes** [Marco-Sulla/python-frozendict#29]
OS version: macOS Big Sur 11.4
Python3 version (python3 -V -V):
```
Python 3.9.0 (default, Nov 13 2020, 17:57:54)
[Clang 10.0.1 (clang-1001.0.46.4)]
```

Steps to reproduce:

```python
>>> from copy import copy, deepcopy
>>>
>>> from frozendict import frozendict
>>>
>>> deepcopy(dict)
<class 'dict'>
>>> deepcopy(dict[str, int])
dict[str, int]
>>>
>>> deepcopy(frozendict)
<class 'frozendict.core.frozendict'>
>>> deepcopy(frozendict[str, int])
{}
```

I don't exactly know _why_ this is happening, but a bit of debugging info:
- `__new__` and `__init__` are never called (but did confirm it is called for something like `frozendict()`)
- `__deepcopy__` _is_ called, but only for the `deepcopy(frozendict[str, int])` case... and then `type(self)` is `dict`, *not* `frozendict` which seems weird.

**Comment by Marco-Sulla** [comment]
Can you give me the result of:

```
import frozendict
frozendict.c_ext
```

**Comment by JacobHayes** [comment]
```
>>> import frozendict
>>> frozendict.c_ext
False
```

**Comment by Marco-Sulla** [comment]
And this is a problem because....?

**Comment by JacobHayes** [comment]
I'm hoping to use `frozendict` with [`pydantic`](https://github.com/samuelcolvin/pydantic) (think: dataclasses, but with runtime type checking/parsing - including dict keys and values). The `pydantic` Models have references to the field types (eg: `frozendict[str, int]`), but occasionally call `deepcopy` (eg: when subclassing). [After a deepcopy](https://github.com/samuelcolvin/pydantic/pull/3138#discussion_r702362327), instead of having `model.__fields__['fieldname'] = frozendict[str, int]`, we end up with `model.__fields__['fieldname'] = {}`, causing a few [other](https://github.com/samuelcolvin/pydantic/issues/3122) issues.

Small example w/ pydantic if it helps:
```python
from frozendict import frozendict
from pydantic import BaseModel

class Base(BaseModel):
    a: frozendict[str, int]

class Sub(Base):
    pass

print(Sub.__fields__["a"].outer_type_)
```

**Comment by JacobHayes** [comment]
I think this is a bug in python's `copy` module - when using `deepcopy` with a `GenericAlias` _and_ a `__deepcopy__` method, the `GenericAlias` is not considered a type and so `copy` fetches `.__deepcopy__` *from the class* and calls it with the memo dict (hence `type(self) is dict`). I'll open a bug upstream.

**Comment by Marco-Sulla** [comment]
I reopen it, since the type hint does not work at all in the C Extension

**Comment by Marco-Sulla** [comment]
Fixed https://github.com/Marco-Sulla/python-frozendict/commit/ecf771ce2f0ad3c8ff9e9059a40f2e9aed1cac6f

**Comment by JacobHayes** [comment]
Thanks. Btw, the original `deepcopy` issue was fixed upstream in https://github.com/python/cpython/pull/28324
