### ISSUE TITLE
[FEATURE] Add `r` operators

### ISSUE THREAD

**Issue by Marco-Sulla** [Marco-Sulla/python-frozendict#3]
`frozendict` now implements `__add__` and `__sub__`. It could implement also `__radd__` and `__rsub__`. So, for example:

`d + fd == fd + d`

where `fd` is a `frozendict` and `d` is a dict-like object.

This could be applied also to #2.

**Comment by lurch** [comment]
I guess this is now defunct too?

**Comment by Marco-Sulla** [comment]
I suppose yes.
