### ISSUE TITLE
Recursively convert dicts in __init__()?

### ISSUE THREAD

**Issue by johnomotani** [Marco-Sulla/python-frozendict#30]
I came across this awesome package looking for a way to convert a `dict` to a hashable thing. However, sometimes I have a `dict` contains other `dict`s, so even if I convert the `dict` to a `frozendict`, the `frozendict` is not hashable, because it contains `dict`s. It would be awesome to have some sort of constructor that could iterate recursively through iterable values and convert any `dict`s to `frozendict`s. I guess this would not be good default behaviour because it might be slow, and switching the behaviour on with a keyword argument to `__new__()` might clash with keys in `**kwargs`, I guess a classmethod might be the best approach?

In my actual use case, I don't expect to have deeply nested inputs, so I can convert `dict`->`frozendict` without worrying about recursion, but it'd be great to have an automagic, general solution!

**Comment by Marco-Sulla** [comment]
It seems to me more a work for [gelidum](https://github.com/diegojromerolopez/gelidum).

**Comment by johnomotani** [comment]
Thanks @Marco-Sulla, `gelidum` is exactly what I was looking for!

**Comment by lurch** [comment]
I've not looked at gelidum in much detail, but is it worth mentioning it as e.g. a "related project" in this repo's README @Marco-Sulla ?

**Comment by Marco-Sulla** [comment]
Well, when gelidum will use frozendict as its immutable map, why not. But I don't think they'll change their implementation.

**Comment by Marco-Sulla** [comment]
Anyway, on a second thought, I think I'll add a `deepfreeze()` method, that will return a new frozendict with nested elements converted so:

* dicts to frozendicts
* lists to tuples
* bytearrays to bytes
* sets to frozensets

Notice that unknown types can't be converted, and the resulting frozendict could not be always hashable.

**Comment by lurch** [comment]
Oh, I hadn't noticed that gelidum was using their own frozendict implementation, rather than your implementation, sorry! :laughing:

**Comment by Marco-Sulla** [comment]
deepfreeze was implemented in 2.4.0. Please read the readme.

Happy 2024 with 2.4.
