### ISSUE TITLE
[FEATURE]  update also for Python 3.6 - 3.8?

### ISSUE THREAD

**Issue by tommy-mor** [Marco-Sulla/python-frozendict#36]
update that returns a new frozendict?

**Comment by Marco-Sulla** [comment]
From python 3.9, you can use the `|` operator.
It's planned to add it for the C extension for python 3.6+. Check the TODO list (dict_or): https://github.com/Marco-Sulla/python-frozendict/issues/34

**Comment by tommy-mor** [comment]
ok cool

**Comment by Marco-Sulla** [comment]
I leave it open until the feature is not implemented :)

**Comment by Marco-Sulla** [comment]
Fixed: https://github.com/Marco-Sulla/python-frozendict/commit/14fc8af0e82c24a393d7e04300d4dfdd33026e82

Unluckily, it seems there's no way to make it working `dict | frozendict == new_merged_dict` in the C extension. In the pure py version it works.
