### ISSUE TITLE
[BUG] Copy `frozenset.__hash__()` method from CPython

### ISSUE THREAD

**Issue by Marco-Sulla** [Marco-Sulla/python-frozendict#4]
The hash method implemented currently is the hash method proposed in the first PEP that proposed a `frozendict`. It's simple, elegant and reliable. <s>The only change is that now uses `tuple` instead of `frozendict`, that's more fast and uses less memory.</s>

Anyway, the creation of a temporary <s>`tuple`</s> `frozenset` is useless. Even if a map usually does not contains more than 20 items, there could be huge dictionaries which hash can't be calculated with the current implementation.

IMHO we should lurk the CPython code of <s>`tuple.__hash__`</s> `frozenset.__hash__`, and convert it in Py code.

**Comment by lurch** [comment]
I dunno where the talk about `tuple` comes from (and I haven't read any CPython source code) but while looking at the current [`__hash__` implementation](https://github.com/Marco-Sulla/python-frozendict/blob/master/frozendict/core.py#L92) I _did_ wonder if the creation of the temporary `frozenset` would be a memory-hog and if it would be better to use something like what https://github.com/slezica/python-frozendict/pull/13 did? :man_shrugging:

**Comment by Marco-Sulla** [comment]
Yes, I restored `frozenset`.

**Comment by Marco-Sulla** [comment]
Implemented by https://github.com/slezica/python-frozendict/commit/4ef25eec7c152008a0e7dbbbb7839a1a53392607
