### ISSUE TITLE
[BUG] Incorrect exception type thrown when doing `attr` assignment using `dict` and `object`.

### ISSUE THREAD

**Issue by Harmouch101** [Marco-Sulla/python-frozendict#57]
OS version: Any
Python3 version: Any

Steps to reproduce:

```python
foo = frozendict({"foo": "bar"})
dict.__setattr__(foo, 'foo', "let's foo this!")
object.__setattr__(foo, 'foo', "let's foo this!")
```

Actual result:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'frozendict.frozendict' object has no attribute 'foo'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'frozendict.frozendict' object has no attribute 'foo'
```

It should instead raize the following:

```python
TypeError: 'frozendict.frozendict' object does not support item assignment
```

Besides, I am pretty amazed that this package is capable of creating actual immutable objects([i thought it is impossible](https://github.com/python-attrs/attrs/issues/962) to do so in python). Kudos. I tried to do similar stuff but wasn't aware of these edge cases. I did also a little comparison between the two packages. Not relevant, but it was a fun project to work on. If you don't mind, I would like to improve the codebase especially [this part ](https://github.com/Marco-Sulla/python-frozendict/blob/3e3c6356d3523872ba1425b1f12c3354ee5075d3/frozendict/core.py#L234-L239), where you can take advantage of decorators like what I did [over here](https://github.com/Harmouch101/frozndict/blob/016dcaa5adafa4223101538684335085dd1da798/frozndict/frozendict.py#L125-L126),  and add type annotation.

Edit 1: Oh! wait... It is actually a feature, not a bug, `__setattr__` would behave the same as `foo.foo = ...` which is not present ~~presumably because the usage of `__slots__`~~. You are absolutely a fu**ing nit-picker. Now, I am wondering how did you prevent these cases: `object.__setattr__` and `dict.__setattr__`.

Edit 2: Figured out the reason why it throws these exceptions because it inherits from `dict`:

```python
>>> foo = {"foo": "bar"}
>>> foo.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'foo'
>>> object.__setattr__(foo, 'foo', 'bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'foo'
```

Good to know.

**Comment by Marco-Sulla** [comment]
> OS version: Any Python3 version: Any
> 
> Steps to reproduce:
> 
> ```python
> foo = frozendict({"foo": "bar"})
> dict.__setattr__(foo, 'foo', "let's foo this!")
> object.__setattr__(foo, 'foo', "let's foo this!")
> ```
> 
> Actual result:
> 
> ```python
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'frozendict.frozendict' object has no attribute 'foo'
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: 'frozendict.frozendict' object has no attribute 'foo'
> ```
> 
> It should instead raize the following:
> 
> ```python
> TypeError: 'frozendict.frozendict' object does not support item assignment
> ```

Well, no. It's actually the right exception. See for example:

```
>>> foo = ()
>>> object.__setattr__(foo, 'foo', "let's foo this!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'foo'
```

> 
> Besides, I am pretty amazed that this package is capable of creating actual immutable objects([i thought it is impossible](https://github.com/python-attrs/attrs/issues/962) to do so in python). 

Well, indeed it's impossible. There's a C Extension that make it really immutable. The pure Python version is not really immutable.

> I would like to improve the codebase especially [this part ](https://github.com/Marco-Sulla/python-frozendict/blob/3e3c6356d3523872ba1425b1f12c3354ee5075d3/frozendict/core.py#L234-L239), where you can take advantage of decorators like what I did [over here](https://github.com/Harmouch101/frozndict/blob/016dcaa5adafa4223101538684335085dd1da798/frozndict/frozendict.py#L125-L126), and add type annotation.

There's another bug report for the type annotations. The main problem is I have no idea how to support them in the C Extension for Python 3.9-. In Python 3.9+ they works.

**Comment by Harmouch101** [comment]
Do you mind doing some refactoring on the codebase?

**Comment by Harmouch101** [comment]
I am asking because there is no contribution guideline in the repo.

**Comment by Harmouch101** [comment]
> Well, indeed it's impossible. There's a C Extension that make it really immutable. The pure Python version is not really immutable.

Now I get it. The python files are not related to the package, right?

**Comment by Marco-Sulla** [comment]
> Do you mind doing some refactoring on the codebase?

What do you have in mind?
