### ISSUE TITLE
[FEATURE] Show `==` being used in the README examples

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#6]
In the list of examples in the README, I wonder if it might be worth demonstrating something like:
```python3
fd4 = frozendict({"Sulla": "Marco", "Hicks": "Bill"})
fd4 is fd
# False

fd4 == fd
# True

fd5 = frozendict({"Hicks": "Bill", "Sulla": "Marco"})
fd5 == fd4
# True
```

Or maybe that's too trivial to be worth demonstrating? :man_shrugging:

**Comment by Marco-Sulla** [comment]
Why not? IMHO you can substitute fd4 with fd5 and remove the last example :)

I do the change or you want to modify it by yourself?

**Comment by lurch** [comment]
Cool, I'll submit a PR tomorrow... (unless you beat me to it :stuck_out_tongue_winking_eye: )
