### ISSUE TITLE
[BUG] Memory leak when constructing empty frozendicts

### ISSUE THREAD

**Issue by squahtx** [Marco-Sulla/python-frozendict#60]
Similar to #55, `frozendict()` and `frozendict({})` leak memory.

OS version: Ubuntu 20.04.4 LTS
Python3 version (python3 -V -V): Python 3.8.10

## Steps to reproduce

Borrowing code from #55:
```py
import resource
import frozendict

print("frozendict version:", frozendict.__version__)
print()

c = 0
while True:
    fz = frozendict.frozendict({})
    
    if (c % 10000) == 0:
        max_rss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        print(f"iteration: {c}, max rss: {max_rss} kb")
    
    c += 1
```

## Actual result
```
frozendict version: 2.3.2

iteration: 0, max rss: 11292 kb
iteration: 10000, max rss: 12188 kb
iteration: 20000, max rss: 12980 kb
iteration: 30000, max rss: 13772 kb
...
iteration: 3150000, max rss: 263252 kb
iteration: 3160000, max rss: 264044 kb
iteration: 3170000, max rss: 265100 kb
```

**Comment by squahtx** [comment]
I think we might be missing a `Py_DECREF(self)` when we decide to return an empty frozendict in `_frozendict_new`?

https://github.com/Marco-Sulla/python-frozendict/blob/8def42ca45c93a626048bc8fcd402f483fbef591/frozendict/src/3_8/frozendictobject.c#L1562-L1575

**Comment by Marco-Sulla** [comment]
Thank you for the report. Fixed in https://github.com/Marco-Sulla/python-frozendict/commit/81e163ad7caa1b9a56b519c2dfa6a527dac3ba64 can you confirm?

**Comment by squahtx** [comment]
That seems to have fixed it. Thank for your the fast response!
Can we have a PyPI release with the fix?

**Comment by Marco-Sulla** [comment]
Done.

**Comment by squahtx** [comment]
Thanks again for getting the bugs fixed!
