### ISSUE TITLE
[BUG] delete method successfully deletes item from frozendict instead of raising error.

### ISSUE THREAD

**Issue by eddiethedean** [Marco-Sulla/python-frozendict#61]
Welcome! You should write in your Bug Report:

OS version (https://www.google.com/search?channel=fs&q=check+os+version&ie=utf-8&oe=utf-8):
macOS Monterey 12.4 

Python3 version (python3 -V -V):
3.10

Steps to reproduce:

1. initialize frozendict2. 
2. call delete method on existing key.

Actual result (with the python stack trace if present):
deleted item is missing from frozendict.

**Comment by Marco-Sulla** [comment]
From README:

delete(key)

It returns a new frozendict without the item corresponding to the key. If the key is not present, a KeyError is raised.
