### ISSUE TITLE
[FEATURE] Python 3.11

### ISSUE THREAD

**Issue by sgn** [Marco-Sulla/python-frozendict#65]
Welcome! Before you write your Feature Request, please read below:

**Is your feature request related to a problem? Please describe.**
Python 3.11 is around the corner. Some packages requires frozendict to work. This is blocking updating Python in distribution

**Describe the solution you'd like**
Support Python 3.11 and maybe 3.12

**Describe alternatives you've considered**

**Additional context**

**Comment by lurch** [comment]
Duplicate of #58 ?
