### ISSUE TITLE
[BUG] isinstance(frozendict(), dict)==False

### ISSUE THREAD

**Issue by ArneBachmannDLR** [Marco-Sulla/python-frozendict#66]
I was assuming that frozendict() inherits from dict and can be typechecked as a dict, but this seems to be wrong:

```python3
>>> isinstance(frozendict(), dict)
False
```

Any ideas how to handle this?

**Comment by lurch** [comment]
Related to #39 ? :shrug:

**Comment by ArneBachmannDLR** [comment]
Not sure, but I resorted to expand my checks to `isinstance(d, (dict, frozendict))` and my function signature to `d:Union[Dict[A,B],frozendict[A,B]]` which seems to work so far.

I think the reason is that Python is duck-typed and doesn't always follow a clear inheritance logic, therefore `isinstance` checks aren't always what you want.

**Comment by Marco-Sulla** [comment]
`frozendict` is immutable, so it can't be a subtype of `dict`, that is mutable. The fact that in the pure py implementation `frozendict` inherits from `dict` is only for speed reasons. The correct check is:

```
from collections.abc import Mapping
isistance(frozendict, Mapping)
```

> Related to #39 ? shrug

No

**Comment by ArneBachmannDLR** [comment]
Thanks! That's more like what I meant.

Small correction: It must be `isinstance(frozendict({1: 1}), Mapping)`
