### ISSUE TITLE
Question about `notimplemented` method

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#7]
Not sure if this counts as an enhancement request, but worth a question anyway...

When I did `dir()` on a `frozendict` object yesterday, I was surprised to see a `notimplemented` method listed!
Looking at the [implementation](https://github.com/Marco-Sulla/python-frozendict/blob/master/frozendict/core.py#L188) should it
 a) have a leading underscore, to mark it as not-a-public-method?
 b) be named something more appropriate like `_raise_not_implemented` ?

**Comment by Marco-Sulla** [comment]
Well, I think I can do better: I can move the function outside the class :)

**Comment by Marco-Sulla** [comment]
Solved with https://github.com/Marco-Sulla/python-frozendict/commit/698abd8a363bf20f07904ff28807d3299a9cf187.

**Comment by lurch** [comment]
Much neater :slightly_smiling_face:
