### ISSUE TITLE
[BUG] Version 2.3.6 appears to have been yanked

### ISSUE THREAD

**Issue by phlax** [Marco-Sulla/python-frozendict#78]
I dont see any evidence of it in pypi but our CI is now permafailing when trying to download the 2.3.6 version

https://dev.azure.com/cncf/envoy/_build/results?buildId=133550&view=logs&j=767be981-567e-57d8-68c3-2140ede0a0bd&t=8a34f9ed-4946-5fcf-7cd6-99c93070884d&l=132

this worked fine until yesterday

**Comment by phlax** [comment]
as it works correctly with `pip-compile` i suspect the hashes have changed

**Comment by Marco-Sulla** [comment]
Your pipeline works on the sdist? Because I removed the sdist package in 2.3.6, since it was broken. It missed the sources of the C Extension, so it produced the pure py version ever.

The new version 2.3.7 should work. Can you confirm it?

**Comment by phlax** [comment]
```diff
-    --hash=sha256:14e376fb0c8fe0b11b77872a84356dfa191b24a240be66bf5ec66d9b0d203bb8 \
```

**Comment by Marco-Sulla** [comment]
Per my previous comment, this is probably the hash of the sdist package. Unluckily, you can't yank single packages of a release, only delete them. Sorry for the confusion and let me know if the problem is fixed with 2.3.7

**Comment by phlax** [comment]
awaiting confirmation

**Comment by phlax** [comment]
confirming that switching to 2.3.7 resolves the issue

**Comment by Marco-Sulla** [comment]
Well, OK, I agree with you. But I suppose it's also good practice to not post a swarm of harsh comments on holidays X-D

Happy Easter.

**Comment by phlax** [comment]
apologies if this was harsh

i really do value the library you maintain and felt this advice was not unreasonable - but yep - happy holidays

**Comment by Marco-Sulla** [comment]
> felt this advice was not unreasonable

No, it was not :)

> i really do value the library you maintain

Thank you. A lot.
