### ISSUE TITLE
[BUG] "functional change" to `__hash__`

### ISSUE THREAD

**Issue by lurch** [Marco-Sulla/python-frozendict#8]
OS version:
Ubuntu 14.04.6 x64

Python3 version (python3 -V -V):
Python 3.6.8 (default, Dec 25 2018, 00:00:00) 
[GCC 4.8.4]

Steps to reproduce:
```python3
>>> from frozendict import frozendict
>>> fd1 = frozendict({'a': 'b', 1:2})
>>> fd2 = frozendict({'a': 'b', 1:2})
>>> fd3 = frozendict({1:2, 'a': 'b'})
>>> fd1 == fd2
True
>>> fd2 == fd3
True
>>> fd1 == fd3
True
>>> hash(fd1)
7248413867072730019
>>> hash(fd2)
7248413867072730019
>>> hash(fd3)
6961149576487961955
```

Note that `fd2 == fd3` but `hash(fd2) != hash(fd3)`. When I tried running this code yesterday (prior to https://github.com/Marco-Sulla/python-frozendict/commit/0125b86bda8903eaeda09ecb438b5207e2f981be ) the hash values for fd2 and fd3 equalled (`hash(fd2) == hash(fd3)`).

**Comment by Marco-Sulla** [comment]
Ok, now I remember why the first time I considered to use `tuple` and I dismissed it...

Fixed with https://github.com/Marco-Sulla/python-frozendict/commit/10303a87861d8f47dac37dfa5550a2a47478b4e7.
