### ISSUE TITLE
[BUG] `frozendict()` vs `frozendict({})` type hints

### ISSUE THREAD

**Issue by GarrisonD** [Marco-Sulla/python-frozendict#83]
```py
from frozendict import frozendict

a = frozendict() # frozendict[str, Any]
b = frozendict({}) # frozendict
```

I believe `frozendict() == frozendict({})`. If not, then it would be valuable to describe the difference in the documentation 📜

**Comment by GarrisonD** [comment]
Hm, very interesting...

When I open your repo in GitHub Codespaces, change `test/typed.py` to:

```
from frozendict import frozendict

reveal_type(frozendict())
reveal_type(frozendict({}))
```

and run `mypy test/typed.py`, I get:

```
test/typed.py:3: note: Revealed type is "frozendict.frozendict[<nothing>, <nothing>]"
test/typed.py:4: note: Revealed type is "frozendict.frozendict[<nothing>, <nothing>]"
Success: no issues found in 1 source file
```

When I do the same in my project, I get:

```
test.py:3: note: Revealed type is "frozendict.frozendict[builtins.str, <nothing>]"
test.py:4: note: Revealed type is "frozendict.frozendict[<nothing>, <nothing>]"
```

I had `mypy` of version 1.4.1, upgraded to 1.5.1 but the result is the same 🤔

**Comment by Marco-Sulla** [comment]
Can you test it in a release tag?

**Comment by GarrisonD** [comment]
OK, the issue presents on `v2.3.8` and was fixed in https://github.com/Marco-Sulla/python-frozendict/commit/5f0c05cd23d6e9b542eed9869b80dfb2360b2936.

Are you going to release a new version soon? 🙏

**Comment by Marco-Sulla** [comment]
Sorry for the delay, `2.3.9` released :)
