### ISSUE TITLE
[BUG] Union of frozendict and frozendict results in dict

### ISSUE THREAD

**Issue by rindPHI** [Marco-Sulla/python-frozendict#84]
The union of a frozendict with `|` should again result in a frozendict, but does actually result in a mutable dict.

OS version: macOS 13.5.2
frozendict version: 2.3.8
Python3 version (python3 -V -V):  Python 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Steps to reproduce:

```python
In [1]: from frozendict import frozendict
In [2]: a = frozendict({1: 2})
In [3]: type(a | a)
Out[3]: dict
```

Expected result:
`frozendict`

Actual result:
`dict`

**Comment by Marco-Sulla** [comment]
Confirmed. The problem is in the pure py implementation, probably in the left operand
