### ISSUE TITLE
[FEATURE] Licensing permission for open-source projects that (seemingly) cannot comply with LGPL terms due to interfacing with commercial data

### ISSUE THREAD

**Issue by dem1995** [Marco-Sulla/python-frozendict#92]
Background:
I am part of a group working on an open-source (MIT-licensed) project, [Archipelago](https://github.com/ArchipelagoMW/Archipelago), that adds networking and shared progression to video games. Under the terms of the LGPL, required data to run a program must be released in non-LGPL combined works that link LGPL software.

Problem:
A different gaming project was informed by the Free Software Foundation that in order for their project to be compliant, the commercial video-game ROM that their project modified needed to be included. This is obviously not possible, as users need to use their own purchased games for ours and others' projects to remain legal. We are unsure of whether this LGPL ruling applies to our project (or if the licence would hold up in this way in court), but this possible forced noncompliance being the case, we are not eager to include software that might lead to legal issues down the line.

Solution:
I am hoping that `frozendict` might be made available to our project or projects in similar positions to our project, to the extent that the `frozendict` developers are comfortable doing so. For example, "we the `frozendict` team, license `frozendict` for video-game modding projects to use `frozendict` if complying with `frozendict`'s licensing in all ways but the redistribution of the video games being modified or the hardware/software required to run those games".

Some other solutions to this might be (where the above is #2):
1. Permission from the `frozendict` team for Archipelago to use `frozendict` if complying with `frozendict`'s licensing in all ways but the redistribution of the video games being modified or the hardware/software required to run those games
2. Permission from the `frozendict` team for open-source video-game modding projects to use `frozendict` if complying with `frozendict`'s licensing in all ways but the redistribution of the video games being modified or the hardware/software required to run those games
3. Permission from the `frozendict` team for projects to use `frozendict` if complying with `frozendict`'s licensing in all ways but the redistribution of video games or hardware/software/data that development members have no control over
4. A modification of the LGPL licence to allow one of 1-3

Thank you for your time and consideration of this request, as well as your continued efforts on the `frozendict` library.

**Comment by Marco-Sulla** [comment]
> A different gaming project was informed by the Free Software Foundation that in order for their project to be compliant, the commercial video-game ROM that their project modified needed to be included.

This sounds to me very strange. LGPL is the *LESSER* GPL, it can be used with proprietary software:

> The license allows developers and companies to use and integrate a software component released under the LGPL into their own (even [proprietary](https://en.wikipedia.org/wiki/Proprietary_software)) software without being required by the terms of a strong [copyleft](https://en.wikipedia.org/wiki/Copyleft) license to release the source code of their own components.

From https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

Can I have a link about what are you saying?

**Comment by dem1995** [comment]
My understanding was that the ROMs constituted [corresponding application code](https://www.gnu.org/licenses/lgpl-3.0.html#:~:text=The%20%E2%80%9CCorresponding%20Application%20Code%E2%80%9D%20for%20a%20Combined%20Work%20means%20the%20object%20code%20and/or%20source%20code%20for%20the%20Application%2C%20including%20any%20data%20and%20utility%20programs%20needed%20for%20reproducing%20the%20Combined%20Work%20from%20the%20Application%2C%20but%20excluding%20the%20System%20Libraries%20of%20the%20Combined%20Work) despite not being distributed with the application, but I was/am pretty confused by this, too, though, given the LGPL's stated purpose (and the fact that seemingly this problem could be removed by just bringing an LGPL project into an LGPL-complying non-LGPL project, then using that secondary project directly). The licensing conversation happened before I joined the community in question, so it's possible something became misconstrued- I've reached out for more clarification on the other end and will let you know when I hear more.

**Comment by Marco-Sulla** [comment]
Long time passed, closing here.
